all:
  children:
    proxmox_docker:
      hosts:
        proxmox-docker-vm:
    linode_docker:
      hosts:
        linode-docker-vm:
    docker_vms:
      children:
        proxmox_docker: null
        linode_docker: null
