---
all:
  children:
    servers:
      hosts:
        proxmox:
    proxmox_docker:
      hosts:
        proxmox-docker-vm:
    linode_docker:
      hosts:
        linode-docker-vm:
    docker_vms:
      children:
        proxmox_docker:
        linode_docker:
    workstations:
      hosts:
        workstation-01:
