---
- name: Deploy Transmission
  hosts: proxmox-docker-vm
  become: true
  roles:
    - docker_app
  vars:
    docker_app_name: transmission
    docker_app_data_dirs:
      - wireguard
      # skipping transmission/config because I need to set a different user/group owner
      # - transmission/config
