---
- name: Deploy Gatus Container
  hosts: docker_vms
  become: yes
  roles:
    - docker_app
  vars:
    app_name: gatus
    app_data_dirs:
      - config
      - db
    app_config_templates:
      - src: "{{ inventory_hostname }}/config.yaml.j2"
        dest: config/config.yaml
