---
- name: Deploy Syncthing Container
  hosts: proxmox-docker-vm
  become: true
  roles:
    - docker_app
  vars:
    docker_app_name: syncthing
    docker_app_owner: "{{ media.puid }}"
    docker_app_group: "{{ media.pgid }}"
