---
- name: Deploy Gatus Container
  hosts: docker_vms
  become: true
  roles:
    - docker_app
  vars:
    docker_app_name: gatus
    docker_app_data_dirs:
      - config
      - db
    docker_app_config_templates:
      - src: "{{ inventory_hostname }}/config.yaml.j2"
        dest: config/config.yaml
