---
- name: Deploy Transmission
  hosts: proxmox-docker-vm
  become: yes
  roles:
    - docker_app
  vars:
    app_name: transmission
    app_data_dirs:
      - wireguard
      # skipping transmission/config because I need to set a different user/group owner
      # - transmission/config
