[http.middlewares]
  [http.middlewares.chain-no-auth]
    [http.middlewares.chain-no-auth.chain]
      middlewares = ["rate-limit", "security-headers", "compress"]
  [http.middlewares.chain-no-auth-without-rate-limit]
    [http.middlewares.chain-no-auth-without-rate-limit.chain]
      middlewares = ["security-headers", "compress"]
  [http.middlewares.chain-basic-auth]
    [http.middlewares.chain-basic-auth.chain]
      middlewares = ["rate-limit", "security-headers", "compress", "basic-auth"]